"""edm model

Revision ID: 3667ee21596a
Revises: 
Create Date: 2023-05-17 09:56:04.515146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3667ee21596a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommadations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age_limit', sa.String(), nullable=True),
    sa.Column('camping_availability', sa.String(), nullable=True),
    sa.Column('festival_capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('festivals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('festivals')
    op.drop_table('artists')
    op.drop_table('accommadations')
    # ### end Alembic commands ###
